name: edgar
description: "Flutter plugin providing library components used in the edgar apps"
version: 0.1.0
homepage: "https://edgar-sante.fr"
repository: "https://github.com/edgar-care/edgar-UI"

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  easy_autocomplete: ^1.6.0
  flutter_svg: ^2.0.7
  bootstrap_icons: ^1.11.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
